### ISSUE TITLE
Timezones... of course :)

### ISSUE THREAD

**Issue by Manawyrm** [classilla/totp-c64#1]
Hey,

you probably already feared that this would happen: I think the timezone handling code isn't quite correct.
When generating a TOTP secret for b32: JBSWY3DPEHPK3PXP / 48656c6c6f21deadbeef with the following settings:
![](https://screenshot.tbspace.de/fbrsejgcuvn.png)
(for Germany, Central European Time, UTC+1)

I am getting an incorrect result. However, when I'm setting the timezone to PST (-8) and then input the local time in PST, everything works as expected:
![](https://screenshot.tbspace.de/npuyafshgjc.png)

This is a fun project, thanks for writing/posting it.

Note: I don't actually need/want/etc. a fix here, just wanted to notify you of the issue and maybe help others that are wondering why they're not getting a correct result.

Off-topic: Here's a nice unix'y way to convert the baseXX-encoded strings into a compatible hex-string:
```shell
echo -n JBSWY3DPEHPK3PXP | base32 -d | xxd -ps
```

Have a great day,
Tobias

**Comment by classilla** [comment]
That's what I get for copy-pasta. I had the sbc and lda in the wrong order in the TZ adjust code. Subtraction is not commutative!

**Comment by classilla** [comment]
Thanks for the report :) There is now a fixed 0.5.1.

**Comment by Manawyrm** [comment]
Awesome, works as expected now :+1: 
Thank you! :)
