### ISSUE TITLE
BUG: does only work with negative time zones

### ISSUE THREAD

**Issue by schorsch3000** [classilla/totp-c64#2]
Hi,
it seems code generation only works with negative time zones.
Filling everything in according to reality will result in codes displayed, but they are not correct.

I'm living in GMT+1 land, assuming it is 19:00 over here right now.
filling in my key, date, time (19:00:00) and zimezone +1 will result in wrong codes.

filling in a negative timetone eg: -8 and adjusting the current local time (10:00, 8 hours shift for -8 and one for +1 )  and it works just fine.

**Comment by schorsch3000** [comment]
Jep, that's a dup of #1 :)

**Comment by classilla** [comment]
Yes, but thanks!

**Comment by classilla** [comment]
There is now a fixed 0.5.1. Thanks!

**Comment by schorsch3000** [comment]
Thanks :)
