### ISSUE TITLE
Proposal: SNTP as Time Source

### ISSUE THREAD

**Issue by oliverschmidt** [classilla/totp-c64#3]
There are quite some 6502 machines in the wild (and several emulators), which are equipped with an Ethernet device. For those devices, there's a 6502 library to get the current time from an SNTP server. It would be nice to be able to use that for TOTP-C64.

The API:
https://github.com/cc65/ip65/blob/main/ip65/sntp.s#L63-L69

The supported devices:
http://wiki.icomp.de/wiki/RR-Net
https://www.ide64.org/eth64.html
https://web.archive.org/web/20150323031638/http://a2retrosystems.com/products.htm
https://a2retrosystems.com/products.htm
https://web.archive.org/web/20010331001718/http://lancegs.a2central.com:80/
https://www.atari8ethernet.com/

BTW...

If the BASIC code were replaced with C code for the cc65 C compiler and the XA code were modified for the cc65 macro assembler, than the cc65 toolchain would create complete programs for the _C64_, _C128_, _Apple II_ and _8bit Atari_ out of the box without any additional tooling.

The library mentioned above for SNTP is already fully integrated into the cc65 toolchain. Therefore, the overall process of getting the time from an SNTP server requires for a C program these 4 simple calls:
https://github.com/cc65/ip65/blob/main/apps/date65.c#L98
https://github.com/cc65/ip65/blob/main/apps/date65.c#L104
https://github.com/cc65/ip65/blob/main/apps/date65.c#L110
https://github.com/cc65/ip65/blob/main/apps/date65.c#L117

**Comment by classilla** [comment]
I appreciate the thought, but as I said in the readme, I'm not undertaking any massive refactoring, which both of these seem to require. Feel free to fork the project if you like, I'd be interested to see any work you do.
